# Generated by Django 5.0 on 2023-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.SmallIntegerField(verbose_name='Доступное количество')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
