# Generated by Django 5.0 on 2023-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_available_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='priducts',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment_to_order',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к заказу'),
        ),
    ]
